name: "Family Household Manager"
version: "1.0.0"
slug: family-chores
description: "Self-hosted household management for families"
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "Web interface"
webui: "http://[HOST]:[PORT:3000]"
startup: application
boot: auto
init: false
map:
  - data:rw
