name: "HomeHero"
version: "1.2.3"
slug: homehero
description: "Gamified chore tracking and rewards for families"
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
ingress: true
ingress_port: 3000
panel_icon: "mdi:trophy"
panel_title: "HomeHero"
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "Web interface (direct access)"
webui: "http://[HOST]:[PORT:3000]"
startup: application
boot: auto
init: false
map:
  - data:rw
